version: '3.8'

services:
  postgres:
    image: postgres:14.0
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: dockette/adminer:full
    ports:
      - 8050:8050
  backend_1:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8005
    ports:
      - "8005:8000"
    depends_on:
      - postgres
  backend_2:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8006
    ports:
      - "8006:8000"
    depends_on:
      - postgres
  backend_3:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8007
    ports:
      - "8007:8000"
    depends_on:
      - postgres
  nginx:
    image: byjg/nginx-extras:1.21
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert:/etc/stockf.com
      - ./django/templates/stock:/var/www/react
    depends_on:
      - postgres
      - backend
      - backend_2
      - backend_3

