version: '3.8'

services:
  backend_1:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8005
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - postgres
  backend_2:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8006
    env_file:
      - .env
    ports:
      - "8006:8000"
    depends_on:
      - postgres
  backend_3:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8007
    env_file:
      - .env
    ports:
      - "8007:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres_data:
