version: '3.8'

services:
  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
  adminer:
    image: dockette/adminer:full
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
  backend:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./react/stockapi
    volumes:
      - react_build:/react/build
  nginx:
    image: byjg/nginx-extras:1.21
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/react
    depends_on:
      - postgres
      - backend
      - frontend
volumes:
  react_build: