# Generated by Django 2.2.10 on 2021-12-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('ticket', models.TextField(max_length=5)),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_info_id', to='stock.SourceInfo')),
            ],
            options={
                'ordering': ['ticket'],
            },
        ),
        migrations.CreateModel(
            name='StockByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(null=True)),
                ('avg_price', models.IntegerField(null=True)),
                ('max_price', models.IntegerField(null=True)),
                ('forecast_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('outdated_status', models.BooleanField(default=False)),
                ('final_accuracy', models.IntegerField(null=True)),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_info_id', to='stock.StockInfo')),
            ],
            options={
                'ordering': ['forecast_date'],
            },
        ),
    ]
